"""Ephemeral per-sandbox TLS certificate generation.

Generates a short-lived CA + server cert pair for each sandbox so the
runner↔sandbox channel is encrypted without trusting the host network.
The CA cert stays with the runner (for verification); the server
cert+key are injected into the sandbox container.
"""

from __future__ import annotations

import datetime
import logging
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)


class TLSMode(str, Enum):
    DISABLED = "disabled"
    APP = "app"       # ephemeral certs generated by the harness
    MESH = "mesh"     # service-mesh provides transport security


@dataclass(frozen=True)
class EphemeralCerts:
    ca_cert_pem: bytes
    server_cert_pem: bytes
    server_key_pem: bytes
    valid_seconds: int = 600


def get_tls_mode(env_value: str = "") -> TLSMode:
    v = env_value.strip().lower()
    if v == "app":
        return TLSMode.APP
    if v == "mesh":
        return TLSMode.MESH
    return TLSMode.DISABLED


def generate_ephemeral_certs(
    common_name: str,
    *,
    san_dns: list[str] | None = None,
    valid_seconds: int = 600,
) -> EphemeralCerts:
    """Generate a self-signed CA and server certificate pair.

    Uses EC P-256 keys (~2 ms vs ~100 ms for RSA) with a short validity
    window to bound blast radius.
    """
    try:
        from cryptography import x509
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.x509.oid import NameOID
    except ImportError as exc:
        raise RuntimeError(
            "TLS cert generation requires the 'cryptography' package. "
            "Install it with: pip install cryptography"
        ) from exc

    now = datetime.datetime.now(datetime.timezone.utc)
    expiry = now + datetime.timedelta(seconds=valid_seconds)

    # CA key + self-signed cert
    ca_key = ec.generate_private_key(ec.SECP256R1())
    ca_name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "sandbox-ca")])
    ca_cert = (
        x509.CertificateBuilder()
        .subject_name(ca_name)
        .issuer_name(ca_name)
        .public_key(ca_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(expiry)
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .sign(ca_key, hashes.SHA256())
    )

    # Server key + CA-signed cert
    srv_key = ec.generate_private_key(ec.SECP256R1())
    san_names: list[x509.GeneralName] = [
        x509.DNSName(common_name),
        x509.DNSName("localhost"),
        x509.IPAddress(
            __import__("ipaddress").IPv4Address("127.0.0.1")
        ),
    ]
    for dns in san_dns or []:
        san_names.append(x509.DNSName(dns))

    srv_cert = (
        x509.CertificateBuilder()
        .subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, common_name)]))
        .issuer_name(ca_name)
        .public_key(srv_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(expiry)
        .add_extension(x509.SubjectAlternativeName(san_names), critical=False)
        .sign(ca_key, hashes.SHA256())
    )

    return EphemeralCerts(
        ca_cert_pem=ca_cert.public_bytes(serialization.Encoding.PEM),
        server_cert_pem=srv_cert.public_bytes(serialization.Encoding.PEM),
        server_key_pem=srv_key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        ),
        valid_seconds=valid_seconds,
    )
